### ISSUE TITLE
onSessionUpdate wont load donation name

### ISSUE THREAD

**Issue by Kraantje85** [StreamElements/widgets#23]
Hi,

I am building a widget but i getting something not right. With this code everything is working and getting updated except for one value and thats the name of the "tip-session-top-donation". Everything loads fine with the "onWidgetLoad" but when i send a simulation donation i get the text "tip-session-top-donation" as name, the amount is updating fine.

Does somebody know what i do wrong?

    window.addEventListener('onWidgetLoad', function (obj) {
        let data = obj["detail"]["session"]["data"];

        $("#top-dono .name").text(data["tip-session-top-donation"]["name"]);
        $("#top-dono .amount").text("€" + data["tip-session-top-donation"]["amount"]);
        $("#sub .name").text(data["subscriber-latest"]["name"]);
    });

    window.addEventListener('onSessionUpdate', function (obj) {
        const data = obj.detail.session;
  
        $("#top-dono .name").text(data["tip-session-top-donation"]["name"]);
        $("#top-dono .amount").text("€" + data["tip-session-top-donation"]["amount"]);
        $("#sub .name").text(data["subscriber-latest"]["name"]);
  
        updateEvent(data);
    });

**Comment by nmynarcik** [comment]
Hey there! If you want to snag the top donator's name, you can get it from `tip-session-top-donator`. You can see more with an [example here](https://github.com/StreamElements/widgets/blob/master/CustomCode.md#on-session-update).
