### ISSUE TITLE
TextArea field

### ISSUE THREAD

**Issue by z0fa** [StreamElements/widgets#36]
Hey it would be great to have a textarea field for the custom widgets, thanks 🙌

**Comment by RedSeal** [comment]
Hey there! Good idea. You can now do something like the below to get a `<textarea>`.  Set it up how you would a regular textfield but add `"mode": "textarea"`. 

**Example:**
```
{
  "myTextArea": {
    "type": "text",
    "label": "This is my TextArea Label",
    "value": "My textarea value",
    "mode": "textarea"
  }
}
```
