### ISSUE TITLE
[BUG] Template string for AlertBox  image is always the default

### ISSUE THREAD

**Issue by MichaelMelena** [StreamElements/widgets#42]
I am using the `{image}` template string to access alert box image.

I have set the image:
![image](https://user-images.githubusercontent.com/24386972/216561915-302e3784-1b66-4f13-8724-278383507c6d.png)
I have checked the HTTP request after selecting the image and it is properly uploaded to SE.

But the value of `{image}` returned is always regardless if the image is set or not.
```https://cdn.streamelements.com/static/alertbox/ALERT_STARS_converted.webm```

**Comment by c4ldas** [comment]
Answered in Discord Server
For those who have the same question, the conversation starts here: 
https://discord.com/channels/141203863863558144/259680142459142144/1071001686774140948

**Comment by MichaelMelena** [comment]
When accessing `{image}` placeholder. Depending on the size of the image there can be delay before the image is loaded. If the delay is too long default value is returned  instead (default value is [https://cdn.streamelements.com/static/alertbox/ALERT_STARS_converted.webm]()).

What solved this issue was to reduce the resolution of the PNG image from 1200x1200px to 200x200px. 
Since SVG files are not supported  if you don't need to change the picture best solution might be to URL encode it into the source files otherwise you should try to keep file size small.
